apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: bookmyshow-backend
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP