apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: bookmyshow-frontend
  ports:
    - port: 80          
      targetPort: 3000  
      nodePort: 30444   
  type: NodePort